version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/library"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Optional: add 'allow' or 'ignore' entries here if you want to skip certain groups or packages.
